version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=gogo-form
      - DATABASE_USER=root
      - DATABASE_PASS=example

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
